### ISSUE TITLE
Any Plan for Kernel 4.4 ?

### ISSUE THREAD

**Issue by liberodark** [ValveSoftware/steamos_kernel#40] opened 2016-04-28 18:00 UTC
On SteamOS 2.0 is better a kernel 4.4 than 4.1 ?

Cordialy

**Comment by JoshuaMurphynz** [comment] 2016-04-28 21:07
If there is a specific reason for the new kernel then they could possibly
test it and eventually put it in

**Comment by johnv-valve** [comment] 2016-05-26 22:19
this is not a bug or issue, closing

**Closed as completed by johnv-valve** 2016-05-26 22:19 UTC
